CREATE TABLE `inscriptions` (
  `id` int NOT NULL,
  `identite` varchar(255) NOT NULL,
  `prenom` varchar(255) NOT NULL,
  `nom` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `tel_mobile` varchar(255) NOT NULL,
  `tel_whatsap` varchar(255) NULL DEFAULT NULL,
  `entreprise` varchar(255) NULL DEFAULT NULL,
  `fonction` varchar(255) NULL DEFAULT NULL,
  `attente_a` varchar(255) NOT NULL,
  `attente_b` varchar(255) NULL DEFAULT NULL,
  `attente_c` varchar(255) NULL DEFAULT NULL,
  `session` varchar(255) NOT NULL,
  `optimal` text NOT NULL,
  `finance` varchar(255) NOT NULL,
  `payement` varchar(255) NOT NULL,
  `information` varchar(255) NOT NULL,
  `nom_recommande` text NULL DEFAULT NULL,
  `formation` varchar(255) NOT NULL,
  `password` varchar(255) NULL,
  `remember_token` varchar(255) NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
);